export const DefaultCountries = [
    // Add US to top for ease of use
    { Id: 'US', Code: 'US', label: 'United States' },
    // Add Countries
    { Id: 'AF', Code: 'AF', label: 'Afghanistan' },
    { Id: 'AX', Code: 'AX', label: 'Aland Islands' },
    { Id: 'AL', Code: 'AL', label: 'Albania' },
    { Id: 'DZ', Code: 'DZ', label: 'Algeria' },
    { Id: 'AS', Code: 'AS', label: 'American Samoa' },
    { Id: 'AD', Code: 'AD', label: 'Andorra' },
    { Id: 'AO', Code: 'AO', label: 'Angola' },
    { Id: 'AI', Code: 'AI', label: 'Anguilla' },
    { Id: 'AQ', Code: 'AQ', label: 'Antarctica' },
    { Id: 'AG', Code: 'AG', label: 'Antigua and Barbuda' },
    { Id: 'AR', Code: 'AR', label: 'Argentina' },
    { Id: 'AM', Code: 'AM', label: 'Armenia' },
    { Id: 'AW', Code: 'AW', label: 'Aruba' },
    { Id: 'AC', Code: 'AC', label: 'Ascension Island' },
    { Id: 'AU', Code: 'AU', label: 'Australia' },
    { Id: 'AT', Code: 'AT', label: 'Austria' },
    { Id: 'AZ', Code: 'AZ', label: 'Azerbaijan' },
    { Id: 'BS', Code: 'BS', label: 'Bahamas' },
    { Id: 'BH', Code: 'BH', label: 'Bahrain' },
    { Id: 'BD', Code: 'BD', label: 'Bangladesh' },
    { Id: 'BB', Code: 'BB', label: 'Barbados' },
    { Id: 'BY', Code: 'BY', label: 'Belarus' },
    { Id: 'BE', Code: 'BE', label: 'Belgium' },
    { Id: 'BZ', Code: 'BZ', label: 'Belize' },
    { Id: 'BJ', Code: 'BJ', label: 'Benin' },
    { Id: 'BM', Code: 'BM', label: 'Bermuda' },
    { Id: 'BT', Code: 'BT', label: 'Bhutan' },
    { Id: 'BO', Code: 'BO', label: 'Bolivia' },
    { Id: 'BA', Code: 'BA', label: 'Bosnia and Herzegovina' },
    { Id: 'BW', Code: 'BW', label: 'Botswana' },
    { Id: 'BV', Code: 'BV', label: 'Bouvet Island' },
    { Id: 'BR', Code: 'BR', label: 'Brazil' },
    { Id: 'IO', Code: 'IO', label: 'British Indian Ocean Territory' },
    { Id: 'VG', Code: 'VG', label: 'British Virgin Islands' },
    { Id: 'BN', Code: 'BN', label: 'Brunei Darussalam' },
    { Id: 'BG', Code: 'BG', label: 'Bulgaria' },
    { Id: 'BF', Code: 'BF', label: 'Burkina Faso' },
    { Id: 'BI', Code: 'BI', label: 'Burundi' },
    { Id: 'KH', Code: 'KH', label: 'Cambodia' },
    { Id: 'CM', Code: 'CM', label: 'Cameroon' },
    // { Id: 'IC', Code: 'IC', label: 'Canary Islands' }, // TODO: duplicate ES
    { Id: 'CA', Code: 'CA', label: 'Canada' },
    { Id: 'CV', Code: 'CV', label: 'Cape Verde' },
    { Id: 'KY', Code: 'KY', label: 'Cayman Islands' },
    { Id: 'CF', Code: 'CF', label: 'Central African Republic' },
    { Id: 'TD', Code: 'TD', label: 'Chad' },
    { Id: 'CL', Code: 'CL', label: 'Chile' },
    { Id: 'CN', Code: 'CN', label: 'China' },
    { Id: 'CX', Code: 'CX', label: 'Christmas Island' },
    { Id: 'CC', Code: 'CC', label: 'Cocos (Keeling) Islands' },
    { Id: 'CO', Code: 'CO', label: 'Colombia' },
    { Id: 'KM', Code: 'KM', label: 'Comoros' },
    { Id: 'CG', Code: 'CG', label: 'Congo' },
    { Id: 'CK', Code: 'CK', label: 'Cook Islands' },
    { Id: 'CR', Code: 'CR', label: 'Costa Rica' },
    { Id: 'CI', Code: 'CI', label: "Côte D'ivoire" },
    { Id: 'HR', Code: 'HR', label: 'Croatia' },
    { Id: 'CU', Code: 'CU', label: 'Cuba' },
    { Id: 'CY', Code: 'CY', label: 'Cyprus' },
    { Id: 'CZ', Code: 'CZ', label: 'Czech Republic' },
    { Id: 'CD', Code: 'CD', label: 'Democratic Republic of the Congo' },
    { Id: 'DK', Code: 'DK', label: 'Denmark' },
    { Id: 'DJ', Code: 'DJ', label: 'Djibouti' },
    { Id: 'DM', Code: 'DM', label: 'Dominica' },
    { Id: 'DO', Code: 'DO', label: 'Dominican Republic' },
    { Id: 'EC', Code: 'EC', label: 'Ecuador' },
    { Id: 'EG', Code: 'EG', label: 'Egypt' },
    { Id: 'SV', Code: 'SV', label: 'El Salvador' },
    { Id: 'GQ', Code: 'GQ', label: 'Equatorial Guinea' },
    { Id: 'ER', Code: 'ER', label: 'Eritrea' },
    { Id: 'EE', Code: 'EE', label: 'Estonia' },
    { Id: 'ET', Code: 'ET', label: 'Ethiopia' },
    { Id: 'FK', Code: 'FK', label: 'Falkland Islands' },
    { Id: 'FO', Code: 'FO', label: 'Faroe Islands' },
    { Id: 'FM', Code: 'FM', label: 'Federated States of Micronesia' },
    { Id: 'FJ', Code: 'FJ', label: 'Fiji' },
    { Id: 'FI', Code: 'FI', label: 'Finland' },
    { Id: 'FR', Code: 'FR', label: 'France' },
    { Id: 'GF', Code: 'GF', label: 'French Guiana' },
    { Id: 'PF', Code: 'PF', label: 'French Polynesia' },
    { Id: 'TF', Code: 'TF', label: 'French Southern Territories' },
    { Id: 'GA', Code: 'GA', label: 'Gabon' },
    { Id: 'GM', Code: 'GM', label: 'Gambia' },
    { Id: 'GE', Code: 'GE', label: 'Georgia' },
    { Id: 'DE', Code: 'DE', label: 'Germany' },
    { Id: 'GH', Code: 'GH', label: 'Ghana' },
    { Id: 'GI', Code: 'GI', label: 'Gibraltar' },
    { Id: 'GR', Code: 'GR', label: 'Greece' },
    { Id: 'GL', Code: 'GL', label: 'Greenland' },
    { Id: 'GD', Code: 'GD', label: 'Grenada' },
    { Id: 'GP', Code: 'GP', label: 'Guadeloupe' },
    { Id: 'GU', Code: 'GU', label: 'Guam' },
    { Id: 'GT', Code: 'GT', label: 'Guatemala' },
    { Id: 'GG', Code: 'GG', label: 'Guernsey' },
    { Id: 'GN', Code: 'GN', label: 'Guinea' },
    { Id: 'GW', Code: 'GW', label: 'Guinea-Bissau' },
    { Id: 'GY', Code: 'GY', label: 'Guyana' },
    { Id: 'HT', Code: 'HT', label: 'Haiti' },
    { Id: 'HM', Code: 'HM', label: 'Heard Island and McDonald Islands' },
    { Id: 'HN', Code: 'HN', label: 'Honduras' },
    { Id: 'HK', Code: 'HK', label: 'Hong Kong' },
    { Id: 'HU', Code: 'HU', label: 'Hungary' },
    { Id: 'IS', Code: 'IS', label: 'Iceland' },
    { Id: 'IN', Code: 'IN', label: 'India' },
    { Id: 'ID', Code: 'ID', label: 'Indonesia' },
    { Id: 'IR', Code: 'IR', label: 'Iran' },
    { Id: 'IQ', Code: 'IQ', label: 'Iraq' },
    { Id: 'IE', Code: 'IE', label: 'Ireland' },
    { Id: 'IM', Code: 'IM', label: 'Isle of Man' },
    { Id: 'IL', Code: 'IL', label: 'Israel' },
    { Id: 'IT', Code: 'IT', label: 'Italy' },
    { Id: 'JM', Code: 'JM', label: 'Jamaica' },
    { Id: 'JP', Code: 'JP', label: 'Japan' },
    { Id: 'JE', Code: 'JE', label: 'Jersey' },
    { Id: 'JO', Code: 'JO', label: 'Jordan' },
    { Id: 'KZ', Code: 'KZ', label: 'Kazakhstan' },
    { Id: 'KE', Code: 'KE', label: 'Kenya' },
    { Id: 'KI', Code: 'KI', label: 'Kiribati' },
    { Id: 'XK', Code: 'XZ', label: 'Kosovo' },
    { Id: 'KW', Code: 'KW', label: 'Kuwait' },
    { Id: 'KG', Code: 'KG', label: 'Kyrgyzstan' },
    { Id: 'LA', Code: 'LA', label: 'Laos' },
    { Id: 'LV', Code: 'LV', label: 'Latvia' },
    { Id: 'LB', Code: 'LB', label: 'Lebanon' },
    { Id: 'LS', Code: 'LS', label: 'Lesotho' },
    { Id: 'LR', Code: 'LR', label: 'Liberia' },
    { Id: 'LY', Code: 'LY', label: 'Libya' },
    { Id: 'LI', Code: 'LI', label: 'Liechtenstein' },
    { Id: 'LT', Code: 'LT', label: 'Lithuania' },
    { Id: 'LU', Code: 'LU', label: 'Luxembourg' },
    { Id: 'MO', Code: 'MO', label: 'Macao' },
    { Id: 'MK', Code: 'MK', label: 'Macedonia' },
    { Id: 'MG', Code: 'MG', label: 'Madagascar' },
    { Id: 'MW', Code: 'MW', label: 'Malawi' },
    { Id: 'MY', Code: 'MY', label: 'Malaysia' },
    { Id: 'MV', Code: 'MV', label: 'Maldives' },
    { Id: 'ML', Code: 'ML', label: 'Mali' },
    { Id: 'MT', Code: 'MT', label: 'Malta' },
    { Id: 'MH', Code: 'MH', label: 'Marshall Islands' },
    { Id: 'MQ', Code: 'MQ', label: 'Martinique' },
    { Id: 'MR', Code: 'MR', label: 'Mauritania' },
    { Id: 'MU', Code: 'MU', label: 'Mauritius' },
    { Id: 'YT', Code: 'YT', label: 'Mayotte' },
    { Id: 'MX', Code: 'MX', label: 'Mexico' },
    { Id: 'MC', Code: 'MC', label: 'Monaco' },
    { Id: 'MN', Code: 'MN', label: 'Mongolia' },
    { Id: 'ME', Code: 'ME', label: 'Montenegro' },
    { Id: 'MS', Code: 'MS', label: 'Montserrat' },
    { Id: 'MA', Code: 'MA', label: 'Morocco' },
    { Id: 'MZ', Code: 'MZ', label: 'Mozambique' },
    { Id: 'MM', Code: 'MM', label: 'Myanmar' },
    { Id: 'NA', Code: 'NA', label: 'Namibia' },
    { Id: 'NR', Code: 'NR', label: 'Nauru' },
    { Id: 'NP', Code: 'NP', label: 'Nepal' },
    { Id: 'NL', Code: 'NL', label: 'Netherlands' },
    { Id: 'AN', Code: 'AN', label: 'Netherlands Antilles' },
    { Id: 'NC', Code: 'NC', label: 'New Caledonia' },
    { Id: 'NZ', Code: 'NZ', label: 'New Zealand' },
    { Id: 'NI', Code: 'NI', label: 'Nicaragua' },
    { Id: 'NE', Code: 'NE', label: 'Niger' },
    { Id: 'NG', Code: 'NG', label: 'Nigeria' },
    { Id: 'NU', Code: 'NU', label: 'Niue' },
    { Id: 'NF', Code: 'NF', label: 'Norfolk Island' },
    { Id: 'KP', Code: 'KP', label: 'North Korea' },
    { Id: 'MP', Code: 'MP', label: 'Northern Mariana Islands' },
    { Id: 'NO', Code: 'NO', label: 'Norway' },
    { Id: 'OM', Code: 'OM', label: 'Oman' },
    { Id: 'PK', Code: 'PK', label: 'Pakistan' },
    { Id: 'PW', Code: 'PW', label: 'Palau' },
    { Id: 'PS', Code: 'PS', label: 'Palestinian Territory, Occupied' },
    { Id: 'PA', Code: 'PA', label: 'Panama' },
    { Id: 'PG', Code: 'PG', label: 'Papua New Guinea' },
    { Id: 'PY', Code: 'PY', label: 'Paraguay' },
    { Id: 'PE', Code: 'PE', label: 'Peru' },
    { Id: 'PH', Code: 'PH', label: 'Philippines' },
    { Id: 'PN', Code: 'PN', label: 'Pitcairn' },
    { Id: 'PL', Code: 'PL', label: 'Poland' },
    { Id: 'PT', Code: 'PT', label: 'Portugal' },
    { Id: 'PR', Code: 'PR', label: 'Puerto Rico' },
    { Id: 'QA', Code: 'QA', label: 'Qatar' },
    { Id: 'MD', Code: 'MD', label: 'Republic of Moldova' },
    { Id: 'RE', Code: 'RE', label: 'Reunion' },
    { Id: 'RO', Code: 'RO', label: 'Romania' },
    { Id: 'RU', Code: 'RU', label: 'Russia' },
    { Id: 'RW', Code: 'RW', label: 'Rwanda' },
    { Id: 'BL', Code: 'BL', label: 'Saint Barthelemy' },
    { Id: 'SH', Code: 'SH', label: 'Saint Helena' },
    { Id: 'KN', Code: 'KN', label: 'Saint Kitts and Nevis' },
    { Id: 'LC', Code: 'LC', label: 'Saint Lucia' },
    { Id: 'MF', Code: 'MF', label: 'Saint Martin' },
    { Id: 'PM', Code: 'PM', label: 'Saint Pierre and Miquelon' },
    { Id: 'VC', Code: 'VC', label: 'Saint Vincent and the Grenadines' },
    { Id: 'WS', Code: 'WS', label: 'Samoa' },
    { Id: 'SM', Code: 'SM', label: 'San Marino' },
    { Id: 'ST', Code: 'ST', label: 'Sao Tome and Principe' },
    { Id: 'SA', Code: 'SA', label: 'Saudi Arabia' },
    { Id: 'SN', Code: 'SN', label: 'Senegal' },
    { Id: 'RS', Code: 'RS', label: 'Serbia' },
    { Id: 'SC', Code: 'SC', label: 'Seychelles' },
    { Id: 'SL', Code: 'SL', label: 'Sierra Leone' },
    { Id: 'SG', Code: 'SG', label: 'Singapore' },
    { Id: 'SX', Code: 'SX', label: 'Sint Maarten' },
    { Id: 'SK', Code: 'SK', label: 'Slovakia' },
    { Id: 'SI', Code: 'SI', label: 'Slovenia' },
    { Id: 'SB', Code: 'SB', label: 'Solomon Islands' },
    { Id: 'SO', Code: 'SO', label: 'Somalia' },
    { Id: 'ZA', Code: 'ZA', label: 'South Africa' },
    { Id: 'GS', Code: 'GS', label: 'South Georgia' },
    { Id: 'KR', Code: 'KR', label: 'South Korea' },
    { Id: 'ES', Code: 'ES', label: 'Spain' },
    { Id: 'LK', Code: 'LK', label: 'Sri Lanka' },
    { Id: 'SD', Code: 'SD', label: 'Sudan' },
    { Id: 'SR', Code: 'SR', label: 'Suriname' },
    { Id: 'SJ', Code: 'SJ', label: 'Svalbard and Jan Mayen' },
    { Id: 'SZ', Code: 'SZ', label: 'Swaziland' },
    { Id: 'SE', Code: 'SE', label: 'Sweden' },
    { Id: 'CH', Code: 'CH', label: 'Switzerland' },
    { Id: 'SY', Code: 'SY', label: 'Syrian Arab Republic' },
    { Id: 'TW', Code: 'TW', label: 'Taiwan' },
    { Id: 'TJ', Code: 'TJ', label: 'Tajikistan' },
    { Id: 'TZ', Code: 'TZ', label: 'Tanzania' },
    { Id: 'TH', Code: 'TH', label: 'Thailand' },
    { Id: 'TL', Code: 'TL', label: 'Timor-Leste' },
    { Id: 'TG', Code: 'TG', label: 'Togo' },
    { Id: 'TK', Code: 'TK', label: 'Tokelau' },
    { Id: 'TO', Code: 'TO', label: 'Tonga' },
    { Id: 'TT', Code: 'TT', label: 'Trinidad and Tobago' },
    { Id: 'TA', Code: 'TA', label: 'Tristan da Cunha' },
    { Id: 'TN', Code: 'TN', label: 'Tunisia' },
    { Id: 'TR', Code: 'TR', label: 'Turkey' },
    { Id: 'TM', Code: 'TM', label: 'Turkmenistan' },
    { Id: 'TC', Code: 'TC', label: 'Turks and Caicos Islands' },
    { Id: 'TV', Code: 'TV', label: 'Tuvalu' },
    { Id: 'UG', Code: 'UG', label: 'Uganda' },
    { Id: 'UA', Code: 'UA', label: 'Ukraine' },
    { Id: 'AE', Code: 'AE', label: 'United Arab Emirates' },
    { Id: 'GB', Code: 'GB', label: 'United Kingdom' },
    { Id: 'UM', Code: 'UM', label: 'United States Minor Outlying Islands' },
    { Id: 'UY', Code: 'UY', label: 'Uruguay' },
    { Id: 'VI', Code: 'VI', label: 'US Virgin Islands' },
    { Id: 'UZ', Code: 'UZ', label: 'Uzbekistan' },
    { Id: 'VU', Code: 'VU', label: 'Vanuatu' },
    { Id: 'VA', Code: 'VA', label: 'Vatican City' },
    { Id: 'VE', Code: 'VE', label: 'Venezuela' },
    { Id: 'VN', Code: 'VN', label: 'Vietnam' },
    { Id: 'WF', Code: 'WF', label: 'Wallis and Futuna' },
    { Id: 'EH', Code: 'EH', label: 'Western Sahara' },
    { Id: 'YE', Code: 'YE', label: 'Yemen' },
    { Id: 'ZM', Code: 'ZM', label: 'Zambia' },
    { Id: 'ZW', Code: 'ZW', label: 'Zimbabwe' },
];