/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-11-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class VariablesForContractFlow {
    
    
    @AuraEnabled
    public string AccountName; 
    @AuraEnabled
    public string ContractEndDate; 
    @AuraEnabled
    public string EmailDeadline;     
    @AuraEnabled
    public string AccountPOCEmail; 
    @AuraEnabled
    public string AccountPOCFirstName;
    @AuraEnabled
    public string LicenseInfo;    
    @AuraEnabled
    public string UpdatedPayment;        
    @AuraEnabled
    public string RenewalTerm;        
    @AuraEnabled
    public string BillingContact;
    @AuraEnabled
    public string AccountFrequency;
    @AuraEnabled
    public string WrittenLanguage;
    
    
   /* @AuraEnabled
    public List<SBQQ__Subscription__c> subList;
    public List<String> subscriptionNames;*/
    
    
}